### PR TITLE
Release v0.12.0

### PR DESCRIPTION
**Pull request by Hoverbear**
##### Description

Prepare the 0.12.0 release.

Still needs a vm test suite run!

##### Checklist

- [ ] Formatted with `cargo fmt`
- [ ] Built with `nix build`
- [ ] Ran flake checks with `nix flake check`
- [ ] Added or updated relevant tests (leave unchecked if not applicable)
- [ ] Added or updated relevant documentation (leave unchecked if not applicable)
- [ ] Linked to related issues (leave unchecked if not applicable)

##### Validating with `install.determinate.systems`

If a maintainer has added the `upload to s3` label to this PR, it will become available for installation via `install.determinate.systems`:

```shell
curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix/pr/$PR_NUMBER | sh -s -- install
```

### CODE REVIEW

**Review by cole-h — APPROVED** [review]
:tada:

**Comment by Hoverbear** [comment]
Seems https://github.com/DeterminateSystems/nix-installer/pull/638 was incomplete, https://github.com/DeterminateSystems/nix-installer/pull/196 also changed some tests. PR incoming.

**Comment by Hoverbear** [comment]
#626 broke the vm-test `uninstallCases.uninstall-shell-profile-clobbered` because we no longer error if the user deleted a file (eg bash.rc) so that test needs to be deleted.

**Comment by Hoverbear** [comment]
Noticed a bug with the configured settings display during my final testing, PR coming.

**Comment by Hoverbear** [comment]
Think that's all the kinks sorted out.

**Pull request merged**
