### PR TITLE
Merge upstream post 0.27.0

### PR DESCRIPTION
**Pull request by abathur**
Reworked history to fold in changes we discussed on tues/weds. @mkenigs

### CODE REVIEW

**Comment by cole-h** [comment]
(Probably meant for this to go against https://github.com/NixOS/experimental-nix-installer :laughing: )

**Comment by mkenigs** [comment]
We haven't made this mistake since the last merge https://github.com/DeterminateSystems/nix-installer/pull/956 😆

**Comment by abathur** [comment]
Lol. Very dramatic conversation going on next to me at the coffee shop. Short-circuiting my attention :)

**Comment by cole-h** [comment]
I'm not fussed! Just figured you might get a bit confused when you try to merge and notice you... can't. :laughing:

**Pull request closed without merging**
