### PR TITLE
Remove nix channel placement

### PR DESCRIPTION
**Pull request by Hoverbear**
##### Description

We don't need to do this at all!

##### Checklist

- [ ] Formatted with `cargo fmt`
- [ ] Built with `nix build`
- [ ] Ran flake checks with `nix flake check`
- [ ] Added or updated relevant tests (leave unchecked if not applicable)
- [ ] Added or updated relevant documentation (leave unchecked if not applicable)
- [ ] Linked to related issues (leave unchecked if not applicable)

##### Validating with `install.determinate.systems`

If a maintainer has added the `upload to s3` label to this PR, it will become available for installation via `install.determinate.systems`:

```shell
curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix/pr/$PR_NUMBER | sh -s -- install
```

### CODE REVIEW

**Review by cole-h — APPROVED** [review]
Seems fine to me. But depending on the 2.14 fallout, we might need to resurrect this for  legacy CLI use cases.

**Comment by Hoverbear** [comment]
Hmmm, should we block this until we find out?

**Comment by cole-h** [comment]
I think it would be fine as-is, but if (when) we switch to 2.14 as the default for this installer, we'll probably want to make sure it's fine this is removed.

**Comment by RaitoBezarius** [comment]
Does this mean that this installer cannot install channels at all?

**Comment by Hoverbear** [comment]
The installer has no options for channels, no.

**Pull request merged**
