### PR TITLE
Move variants/qemu tests to buildkite

### PR DESCRIPTION
**Pull request by Hoverbear**
Move the "variants" to buildkite, do qemu tests there.

### CODE REVIEW

**Comment by Hoverbear** [comment]
I do not love how long this takes, I guess it's because the linux builders don't keep a cache.

**Comment by Hoverbear** [comment]
Having a warm cache would indeed make this a lot faster:

```
harmonic on  main [$?] is 📦 v0.0.0-unreleased via 🦀 v1.66.0 via ❄️  impure (nix-install-shell) took 2s 
❯ hyperfine "nix build .#hydraJobs.vm-test.rhel-v7.x86_64-linux.install-default -L --rebuild"
Benchmark 1: nix build .#hydraJobs.vm-test.rhel-v7.x86_64-linux.install-default -L --rebuild
 ⠴ Current estimate: 27.983 s ███████████████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
 ⠦ Current estimate: 27.983 s ███████████████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
  Time (mean ± σ):     28.005 s ±  0.207 s    [User: 0.027 s, System: 0.040 s]
  Range (min … max):   27.730 s … 28.267 s    10 runs
 
```

**Comment by Hoverbear** [comment]
Seems it's a bit flaky, too.

**Comment by lucperkins** [comment]
Closing due to no longer using Buildkite

**Pull request closed without merging**
