### PR TITLE
Work around macOS compatibility SystemVersion.plist

### PR DESCRIPTION
**Pull request by cole-h**
##### Checklist

- [ ] Formatted with `cargo fmt`
- [ ] Built with `nix build`
- [ ] Ran flake checks with `nix flake check`
- [ ] Added or updated relevant tests (leave unchecked if not applicable)
- [ ] Added or updated relevant documentation (leave unchecked if not applicable)
- [ ] Linked to related issues (leave unchecked if not applicable)

##### Validating with `install.determinate.systems`

If a maintainer has added the `upload to s3` label to this PR, it will become available for installation via `install.determinate.systems`:

```shell
curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix/pr/$PR_NUMBER | sh -s -- install
```

### CODE REVIEW

**Comment by ratbag98** [comment]
@cole-h Life intruded (in the form of a rather nice lunch!) so sorry for the delay. Here are three log files: combined, just stdout and just stderr. I can see that the tests for `is_macos_15_or_later` return `false`. All logs generated from the PR1046 install.sh using something like:

```
sh install_1046.sh plan -vvv > 1046_verbose_all_output.txt 2>&1
```

and differing only in redirection.

[1046_logs.zip](https://github.com/user-attachments/files/16199738/1046_logs.zip)

**Comment by cole-h** [comment]
No apologies necessary, I hope you had a good lunch! I appreciate your willingness to help.

I just pushed a new commit that should hopefully have some more debugging logs that may show where exactly it's failing to do the right thing... Once it's finished uploading (should be very shortly), please give it another shot!

**Comment by ratbag98** [comment]
Running it now and will send you logs, but here's a quick paste of obvious problematic stuff:

```bash
% sh install_1046.sh plan -vvv
info: downloading installer https://install.determinate.systems/nix/rev/1fd88a602faff7e15b450a55a3c31e17d71daed5/nix-installer-x86_64-darwin
[src/settings.rs:223:45] plist::from_file(MACOS_SYSTEM_VERSION_PLIST_PATH) = Ok(
    SystemVersionPlist {
        product_version: "10.16",
    },
)
[src/settings.rs:224:13] &plist = SystemVersionPlist {
    product_version: "10.16",
}
[src/settings.rs:232:13] &major = "10"
[src/settings.rs:232:13] &_rest = "16"
[src/settings.rs:235:13] &major = 10
[src/settings.rs:251:32] maybe_major_version = Some(
    10,
)
[src/settings.rs:253:5] is_macos_15_or_later = false
```

**Comment by cole-h** [comment]
Wow, how confusing. It looks like macOS is known to play tricks with that file: https://stackoverflow.com/questions/69097567/macos-version-returned-as-10-16-instead-of-12-0/ and https://eclecticlight.co/2020/08/13/macos-version-numbering-isnt-so-simple/ show that it's been happening since ~Big Sur.

Could you try rerunning the currently-released installer after setting `export SYSTEM_VERSION_COMPAT=0` in your environment? Hopefully that's all that's needed... but worst case, we may have to parse the output of `sw_vers` :/

**Comment by ratbag98** [comment]
> Could you try rerunning the currently-released installer after setting `export SYSTEM_VERSION_COMPAT=0` in your environment? Hopefully that's all that's needed... but worst case, we may have to parse the output of `sw_vers` :/

Success. After doing the export, the first reference to `is_macos_15_or_later` returns true. As you say, very weird and not terribly helpful on Apple's part!

**Comment by ratbag98** [comment]
I deleted my previous comment since I don't think it's fully fixed it. Give me a second to generate the logs - it looks like the test function does now return true, but it hasn't fixed the user_id (it's still 300).

**Comment by ratbag98** [comment]
[88a6_logs.zip](https://github.com/user-attachments/files/16199953/88a6_logs.zip)

`is_macos_15_or_later` is true, but `nix_build_user_id_base` is 300.

**Comment by cole-h** [comment]
Ah that's right, we re-exec ourselves with sudo... I bet if you run the installer with sudo  directly (so it doesn't try to re-exec itself)

**Comment by ratbag98** [comment]
> ETA: If you run it with sudo and the compat env var _and_ tell sudo to keep current env vars (`sudo -E ...`), it should do the right thing.

You've earned your beverage of choice, large size:

```
% echo $SYSTEM_VERSION_COMPAT
0
% sudo -E sh install_88a6.sh plan -vvv > 88a6_just_stdout.txt 2> 88a6_just_stderr.txt
% sudo -E sh install_88a6.sh plan -vvv > 88a6_all_output.txt 2>&1
% grep build_user_id 88a6_all_output.txt
        "nix_build_user_id_base": 450,
      "nix_build_user_id_base": 450,
```

**Comment by ratbag98** [comment]
The rev ending 01dd doesn't fix it when run from a clean environment (it's reverted to reporting version as 10.16. Can supply full logs if necessary

**Comment by cole-h** [comment]
OK, I think I have one more thing I can attempt. Doing a bit more searching, I found that zig ran into and fixed the same issue: https://github.com/ziglang/zig/pull/7714/. Apparently, the env var only takes effect if it's set in the _parent_ process (that's why it worked when you `export`ed it). They noticed that there's another file, `/System/Library/CoreServices/.SystemVersionPlatform.plist` which is a symlink to `/System/Library/CoreServices/SystemVersion.plist`, but accessing it that way doesn't seem to apply the "compatability versioning" weirdness.

I'll push up another commit shortly (and CI will upload a binary you can try again ~10m after that) that will attempt to read from that. I have faith that that will work, so all that will be left after that is cleanup (probably inspired by that zig PR).

**Comment by ratbag98** [comment]
Ain't life grand? Can confirm presence of the file on my system:

```
% cat /System/Library/CoreServices/.SystemVersionPlatform.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>BuildID</key>
	<string>3AF1D99E-3D69-11EF-B100-6565DCA24FCD</string>
	<key>ProductBuildVersion</key>
	<string>24A5289g</string>
	<key>ProductCopyright</key>
	<string>1983-2024 Apple Inc.</string>
	<key>ProductName</key>
	<string>macOS</string>
	<key>ProductUserVisibleVersion</key>
	<string>15.0</string>
	<key>ProductVersion</key>
	<string>15.0</string>
	<key>iOSSupportVersion</key>
	<string>18.0</string>
</dict>
</plist>
```

**Comment by ratbag98** [comment]
You probably don't want to run an external program, but 

```
% sw_vers --productVersion
15.0
```

is available and the help for it says that it always returns the genuine version.

**Comment by ratbag98** [comment]
Focus Robert, focus.

Success.

```bash
% echo $SYSTEM_VERSION_COMPAT

% sh 0533_install.sh plan -vvv > 0533_just_stdout.txt 2> 0533_just_stderr.txt
Password:
% sh 0533_install.sh plan -vvv > 0533_all_output.txt 2>&1       
% grep build_user_id_base 0533_just_stdout.txt 
        "nix_build_user_id_base": 450,
      "nix_build_user_id_base": 450,
```

**Comment by cole-h** [comment]
@ratbag98 Thanks again for your assistance and feedback in nailing this down! I've just pushed what I hope to be the final version of this PR -- if you happen to have time (and once CI uploads the new version), would you mind re-testing to make sure I didn't flub the logic anywhere?

**Comment by ratbag98** [comment]
> @ratbag98 Thanks again for your assistance and feedback in nailing this down! I've just pushed what I hope to be the final version of this PR -- if you happen to have time (and once CI uploads the new version), would you mind re-testing to make sure I didn't flub the logic anywhere?

Happy to help in the future - this is an excellent project. However... I'm on the road until tomorrow night without my Sequoia machine so I won't be able to test until about 18:00 Whistler time (Pacific something or other).

**Comment by ratbag98** [comment]
@cole-h belated run results here for you. I've attached the customary stdout/stderr/all logs for you.

Here's a plain run of the installer:

```bash
% mkdir candidate
% cd candidate
% curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix/pr/1046 > installer.sh
% echo $SYSTEM_VERSION_COMPAT

 % sh installer.sh install
info: downloading installer https://install.determinate.systems/nix/rev/f019dbfdabd10871e80a16e959a93ec2a8a2ca54/nix-installer-x86_64-darwin
`nix-installer` needs to run as `root`, attempting to escalate now via `sudo`...
Nix install plan (v0.20.1)
Planner: macos (with default settings)

Planned actions:
* Create an encrypted APFS volume `Nix Store` for Nix on `disk1` and add it to `/etc/fstab` mounting on `/nix`
* Extract the bundled Nix (originally from /nix/store/chv9j1lfr92jsy5y12icd6arhsil0fd8-nix-binary-tarball-2.23.3/nix-2.23.3-x86_64-darwin.tar.xz)
* Create a directory tree in `/nix`
* Move the downloaded Nix into `/nix`
* Create build users (UID 451-482) and group (GID 30000)
* Configure Time Machine exclusions
* Setup the default Nix profile
* Place the Nix configuration in `/etc/nix/nix.conf`
* Configure the shell profiles
* Configuring zsh to support using Nix in non-interactive shells
* Configure Nix daemon related settings with launchctl
* Remove directory `/nix/temp-install-dir`
```

I'd say we're good to go.

[candidate.zip](https://github.com/user-attachments/files/16270546/candidate.zip)

**Comment by cole-h** [comment]
Woohoo! Thanks a ton for all your help in tracking this down and testing out fixes!

**Review by grahamc — APPROVED** [review]

**Comment by ratbag98** [comment]
@cole-h I presume a new 0.20.1 release needs to be made for the "normal" installation command to work? Currently it still goes to ids 301-332. Again, this is not an urgent issue for me so I'm more relating this for informational purposes.

```bash
% curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install
info: downloading installer https://install.determinate.systems/nix/tag/v0.20.1/nix-installer-x86_64-darwin
`nix-installer` needs to run as `root`, attempting to escalate now via `sudo`...
Password:
Nix install plan (v0.20.1)
Planner: macos (with default settings)

Planned actions:
* Create an encrypted APFS volume `Nix Store` for Nix on `disk1` and add it to `/etc/fstab` mounting on `/nix`
* Extract the bundled Nix (originally from /nix/store/chv9j1lfr92jsy5y12icd6arhsil0fd8-nix-binary-tarball-2.23.3/nix-2.23.3-x86_64-darwin.tar.xz)
* Create a directory tree in `/nix`
* Move the downloaded Nix into `/nix`
* Create build users (UID 301-332) and group (GID 30000)
* Configure Time Machine exclusions
* Setup the default Nix profile
* Place the Nix configuration in `/etc/nix/nix.conf`
* Configure the shell profiles
* Configuring zsh to support using Nix in non-interactive shells
* Configure Nix daemon related settings with launchctl
* Remove directory `/nix/temp-install-dir`
```

**Comment by cole-h** [comment]
Yep! I was planning on releasing a 0.20.2 with this fix tomorrow. For now, you can just use `install.determinate.systems/nix/branch/main`

**Comment by cole-h** [comment]
@ratbag98 Sorry for the delay -- 0.20.2 has now been released and is available to `curl`!

**Comment by ratbag98** [comment]
@cole-h let joy be unconfined, let there be dancing in the streets. Build user id 451 correctly selected, nix installing as we speak. Well done and thanks.

And don't worry about the delay, I got my first positive COVID test on Friday (I'm always behind the curve) and have been feeling substantially below par.

**Pull request merged**
