### PR TITLE
Be more friendly to light terminals

### PR DESCRIPTION
**Pull request by Hoverbear**
2023-01-03-115229_screenshot

Fixes this!

### CODE REVIEW

**Review by lheckemann — APPROVED** [review]

**Comment by Hoverbear** [comment]
Dangit, let me fix that.

**Review by lheckemann — APPROVED** [review]
Looks good now :)

**Comment by lheckemann** [comment]
Argh and of course I botched the merge.

**Comment by Hoverbear** [comment]
:rofl:

**Pull request merged**
