### PR TITLE
Nix 2.13.3 -> 2.15.0

### PR DESCRIPTION
**Pull request by grahamc**
##### Description

Closes https://github.com/DeterminateSystems/nix-installer/pull/286.

##### Checklist

- [ ] Formatted with `cargo fmt`
- [ ] Built with `nix build`
- [ ] Ran flake checks with `nix flake check`
- [ ] Added or updated relevant tests (leave unchecked if not applicable)
- [ ] Added or updated relevant documentation (leave unchecked if not applicable)
- [ ] Linked to related issues (leave unchecked if not applicable)

##### Validating with `install.determinate.systems`

If a maintainer has added the `upload to s3` label to this PR, it will become available for installation via `install.determinate.systems`:

```shell
curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix/pr/$PR_NUMBER | sh -s -- install
```

### CODE REVIEW

**Comment by grahamc** [comment]
The path that we care about here needs to be updated here, yeah?

https://github.com/DeterminateSystems/nix-installer/blob/8bb37f1bcff99299849309e7ba3bf5fffdae8d22/src/action/common/configure_shell_profile.rs#L151-L160

**Comment by grahamc** [comment]
Instead of writing out the /nix/var/nix.... path, we need to update to match this commit: https://github.com/NixOS/nix/commit/2384d360839e27edb3c928da858ec911415c8b4d

...which implies we need to capture the XDG_STATE_HOME value from the parent before we sudo and pass it through. If XDG_STATE_HOME isn't set, default to $HOME/.local/state -- again captured before we sudo.

**Comment by Hoverbear** [comment]
Doing a full VM/container test pass on this.

**Comment by Hoverbear** [comment]
Passes! :star:

**Review by Hoverbear — APPROVED** [review]

**Pull request merged**
