### PR TITLE
Release v0.0.2

### PR DESCRIPTION
**Pull request by Hoverbear**
Includes this milestone: https://github.com/DeterminateSystems/nix-installer/milestone/1?closed=1

### CODE REVIEW

**Review by cole-h — APPROVED** [review]
:shipit:

**Comment by Hoverbear** [comment]
Maybe we should include #194

**Comment by cole-h** [comment]
We could always release a v0.0.3 with that in ;)

**Comment by Hoverbear** [comment]
#199 should have been part of this.

**Pull request merged**
