### PR TITLE
Let typescript action set runner as trusted and do Github path

### PR DESCRIPTION
**Pull request by Hoverbear**
##### Description

Reflects https://github.com/DeterminateSystems/nix-installer-action/pull/34's improvements

##### Checklist

- [ ] Formatted with `cargo fmt`
- [ ] Built with `nix build`
- [ ] Ran flake checks with `nix flake check`
- [ ] Added or updated relevant tests (leave unchecked if not applicable)
- [ ] Added or updated relevant documentation (leave unchecked if not applicable)
- [ ] Linked to related issues (leave unchecked if not applicable)

##### Validating with `install.determinate.systems`

If a maintainer has added the `upload to s3` label to this PR, it will become available for installation via `install.determinate.systems`:

```shell
curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix/pr/$PR_NUMBER | sh -s -- install
```

### CODE REVIEW

**Review by cole-h — COMMENTED** [review]
LGTM, but not approving until the action port is merged and the action references here point back to the action's `main` ref.

**Comment by Hoverbear** [comment]
Hm....

**Comment by Hoverbear** [comment]
This needs some touching, notably for the reasons detailed in https://github.com/DeterminateSystems/nix-installer-action/pull/34#issuecomment-1636127448

**Comment by Hoverbear** [comment]
This now creates that `GITHUB_PATH` file as writable (by anyone). This should remove any issues folks face as we move the logic into the action over the next period of the time.

**Comment by Hoverbear** [comment]
It'd be really nice to be able to encourage users to upgrade their action so we could one day remove this...

**Pull request merged**
